export const AI_KEYWORDS = [
  'artificial intelligence',
  'machine learning',
  'deep learning',
  'neural network',
  'AI model',
  'GPT',
  'LLM',
  'large language model',
  'generative AI',
  'computer vision',
  'natural language processing',
  'NLP',
  'transformer',
  'ChatGPT',
  'OpenAI',
  'Claude',
  'Anthropic',
  'Google AI',
  'Microsoft AI',
  'Meta AI',
  'AI startup',
  'AI funding',
  'AI research',
  'autonomous',
  'robotics',
  'automation',
];

export const TECH_JOB_KEYWORDS = [
  'layoff',
  'hiring',
  'job cut',
  'workforce reduction',
  'employment',
  'tech jobs',
  'engineer',
  'developer',
  'data scientist',
  'ML engineer',
  'AI engineer',
  'talent',
  'restructuring',
  'downsize',
  'expansion',
  'recruiting',
  'career',
  'salary',
  'remote work',
  'tech industry',
  'startup funding',
  'IPO',
  'acquisition',
  'merger',
];

export const US_LOCATIONS = [
  'United States',
  'USA',
  'U.S.',
  'Silicon Valley',
  'San Francisco',
  'Bay Area',
  'New York',
  'Seattle',
  'Boston',
  'Austin',
  'Los Angeles',
  'California',
  'Texas',
  'Washington',
  'Massachusetts',
  'Colorado',
  'Denver',
  'Chicago',
  'Miami',
  'Atlanta',
];
